MODULO_VITAL = "suporte_vida"

RESERVA_NORMAL_MIN = 50
RESERVA_ALERTA_MIN = 25
RESERVA_MODERADA_MAX = 60

COMUNICACAO_NORMAL_MIN = 70
COMUNICACAO_ALERTA_MIN = 30

TEMP_INTERNA_MIN = 18
TEMP_INTERNA_MAX = 26

RADIACAO_ALERTA_MIN = 0.3
RADIACAO_CRITICO_MIN = 0.6
